apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "compositions.fullname" . }}-wait-for-compositions
  labels:
    {{- include "compositions.labels" . | nindent 4 }}
    app.kubernetes.io/component: wait-for-compositions
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"  # Run after composition (weight 10)
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    {{- include "compositions.annotations" . | nindent 4 }}
spec:
  backoffLimit: 10
  template:
    metadata:
      name: {{ include "compositions.fullname" . }}-wait-for-compositions
      labels:
        {{- include "compositions.labels" . | nindent 8 }}
        app.kubernetes.io/component: wait-for-compositions
    spec:
      serviceAccountName: {{ include "compositions.serviceAccountName" . }}
      restartPolicy: OnFailure
      {{- with .Values.jobs.waitForCompositionsJob.securityContext }}
      securityContext:
        runAsNonRoot: {{ .runAsNonRoot }}
        runAsUser: {{ .runAsUser }}
        runAsGroup: {{ .runAsGroup }}
      {{- end }}
      containers:
      - name: kubectl
        image: {{ include "compositions.jobRegistry" . }}/{{ .Values.jobs.waitForCompositionsJob.image.repository }}:{{ .Values.jobs.waitForCompositionsJob.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.jobs.waitForCompositionsJob.image.pullPolicy | default "IfNotPresent" }}
        {{- with .Values.jobs.waitForCompositionsJob.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for CognitoAuthorizedAPI XRD to be established as a CRD..."
          kubectl wait --for=condition=established crd/cognitoauthorizedapis.serverlesspdfchat.shortrib.io --timeout=300s
          if [ $? -ne 0 ]; then
            echo "CognitoAuthorizedAPI XRD failed to become established as a CRD within timeout"
            exit 1
          fi
          
          echo "Waiting for CognitoAuthorizedAPI Composition to be ready..."
          kubectl wait --for=jsonpath='{.metadata.name}' composition.apiextensions.crossplane.io/cognitoauthorizedapis.serverlesspdfchat.shortrib.io --timeout=300s || true
          
          echo "All compositions are ready!"
