apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: Stage
metadata:
  name: {{ .Values.global.environment }}
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    apiIdSelector:
      matchLabels:
        {{- include "serverless-pdf-chat.selectorLabels" . | nindent 8 }}
        api: {{ include "serverless-pdf-chat.fullname" . }}-api
    autoDeploy: true
    tags:
      Name: {{ .Values.global.environment }}
      {{- include "serverless-pdf-chat.tags" . | nindent 6 }}
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
