apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ include "providers.runtimeConfigName" . }}
  labels:
    {{- include "providers.labels" . | nindent 4 }}
  annotations:
    {{- include "providers.annotations" . | nindent 4 }}
spec:
  deploymentTemplate:
    metadata:
      labels:
        {{- include "providers.labels" . | nindent 8 }}
    spec:
      selector: {}
      template:
        metadata:
          labels:
            {{- include "providers.labels" . | nindent 12 }}
        spec:
          securityContext:
            runAsNonRoot: {{ .Values.aws.deploymentRuntimeConfig.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.aws.deploymentRuntimeConfig.securityContext.runAsUser }}
            runAsGroup: {{ .Values.aws.deploymentRuntimeConfig.securityContext.runAsGroup }}
          {{- include "providers.imagePullSecrets" . | nindent 10 }}
          containers:
            - name: package-runtime
              resources:
                limits:
                  cpu: {{ .Values.aws.deploymentRuntimeConfig.resources.limits.cpu }}
                  memory: {{ .Values.aws.deploymentRuntimeConfig.resources.limits.memory }}
                requests:
                  cpu: {{ .Values.aws.deploymentRuntimeConfig.resources.requests.cpu }}
                  memory: {{ .Values.aws.deploymentRuntimeConfig.resources.requests.memory }}
  serviceAccountTemplate:
    metadata:
      labels:
        {{- include "providers.labels" . | nindent 8 }}
