{{- $functionName := "options-handler" }}
{{- $functionConfig := dict "description" "Handles OPTIONS requests for CORS" "repository" "options-handler" "timeout" 3 "memorySize" 128 }}
{{- include "serverless-pdf-chat.lambda-function" (dict "Values" .Values "Release" .Release "Chart" .Chart "functionName" $functionName "functionConfig" $functionConfig) }}
