apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: Integration
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-generate-presigned-url-integration
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
    integration: {{ include "serverless-pdf-chat.fullname" . }}-generate-presigned-url-integration
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    apiIdSelector:
      matchLabels:
        {{- include "serverless-pdf-chat.selectorLabels" . | nindent 8 }}
        api: {{ include "serverless-pdf-chat.fullname" . }}-api
    integrationType: AWS_PROXY
    integrationMethod: POST
    integrationUriSelector:
      matchLabels:
        {{- include "serverless-pdf-chat.selectorLabels" . | nindent 8 }}
        function: {{ include "serverless-pdf-chat.fullname" . }}-generate-presigned-url
    payloadFormatVersion: "2.0"
    connectionType: INTERNET
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
