{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-frontend
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "serverless-pdf-chat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "serverless-pdf-chat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- if .Values.aws.ecrAccessToken }}
      imagePullSecrets:
        - name: {{ include "serverless-pdf-chat.fullname" . }}-ecr-credentials
      {{- else if .Values.frontend.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: {{ include "serverless-pdf-chat.frontendImage" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            - name: VITE_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "serverless-pdf-chat.fullname" . }}-frontend-config
                  key: apiEndpoint
            - name: VITE_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "serverless-pdf-chat.fullname" . }}-frontend-config
                  key: region
            - name: VITE_USER_POOL_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "serverless-pdf-chat.fullname" . }}-frontend-config
                  key: userPoolId
            - name: VITE_USER_POOL_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "serverless-pdf-chat.fullname" . }}-frontend-config
                  key: userPoolClientId
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
