{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-frontend
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "serverless-pdf-chat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
