apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: compositions
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: compositions
    chartVersion: 0.3.1
  namespace: serverless-pdf-chat
  weight: -10

  helmUpgradeFlags:
    - --wait
 
  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values: 
    providers:
      aws:
        waitJob:
          serviceAccountName: kotsadm
