apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: serverless-pdf-chat
spec:
  version: 2.3.1+k8s-1.30
  domains:
    proxyRegistryDomain: images.shortrib.io
    replicatedAppDomain: updates.shortrib.io
  extensions:
    helm:
      repositories:
      - name: crossplane-stable 
        url: https://charts.crossplane.io/stable
      charts:
      - name: crossplane
        chartname: crossplane-stable/crossplane
        namespace: crossplane-system
        version: 1.19.1
