apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: cloud-providers
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: providers
    chartVersion: 0.11.8
  namespace: serverless-pdf-chat
  weight: -30

  helmUpgradeFlags:
    - --wait
