apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: serverless-pdf-chat
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: serverless-pdf-chat
    chartVersion: 0.13.35
  namespace: serverless-pdf-chat
  weight: 0 

  helmUpgradeFlags:
    - --wait
 
  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values: 
    aws:
      accountId: '{{repl ConfigOption "aws_account_id" }}'
      region: '{{repl ConfigOption "aws_region" }}'

    global:
      images:
        pullSecrets:
          - '{{repl ImagePullSecretName}}'

  optionalValues:
    - when: '{{repl HasLocalRegistry}}'
      recursiveMerge: true
      values: 
        global:
          images: 
            registry: '{{repl LocalRegistryHost}}'

    - when: '{{repl not HasLocalRegistry}}'
      recursiveMerge: true
      values: 
        global:
          images: 
            registry: 'images.shortrib.io/proxy/{{repl LicenseFieldValue "appSlug"}}/429114214526.dkr.ecr.us-west-2.amazonaws.com'
