# Default values for crossplane-providers chart
nameOverride: ""
fullnameOverride: ""

aws:
  # AWS region where resources will be provisioned
  region: "us-west-2"
  # Default deployment runtime configuration
  defaultDeploymentConfig:
    # Resource limits for provider controllers
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    # Security context for provider controllers
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
  # AWS provider configurations
  providers:
    # Registry for all providers
    registry: "xpkg.upbound.io/upbound"
    iam:
      package: "provider-aws-iam"
      version: "v1.21.1"
      controllerConfig: {}
    s3:
      package: "provider-aws-s3"
      version: "v1.21.1"
      controllerConfig: {}
    dynamodb:
      package: "provider-aws-dynamodb"
      version: "v1.21.1"
      controllerConfig: {}
    lambda:
      package: "provider-aws-lambda"
      version: "v1.21.1"
      controllerConfig: {}
    sqs:
      package: "provider-aws-sqs"
      version: "v1.21.1"
      controllerConfig: {}
    apigatewayv2:
      package: "provider-aws-apigatewayv2"
      version: "v1.21.1"
      controllerConfig: {}
    cognitoidp:
      package: "provider-aws-cognitoidp"
      version: "v1.21.1"
      controllerConfig: {}
    bedrock:
      package: "provider-aws-bedrock"
      version: "v1.21.1"
      controllerConfig: {}
    cloudfront:
      package: "provider-aws-cloudfront"
      version: "v1.21.1"
      controllerConfig: {}
    secretsmanager:
      package: "provider-aws-secretsmanager"
      version: "v1.21.1"
      controllerConfig: {}

kubernetes:
  provider:
    version: "v0.17.2"
    registry: "xpkg.upbound.io/upbound"
