apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ include "providers.fullname" . }}-aws-dynamodb
  labels:
    {{- include "providers.labels" . | nindent 4 }}
  annotations:
    {{- include "providers.annotations" . | nindent 4 }}
spec:
  package: {{ include "providers.packageUrl" (dict "Values" .Values "providerName" "dynamodb") }}
  skipDependencyResolution: true
  runtimeConfigRef:
    name: {{ include "providers.runtimeConfigName" . }}
  {{- include "providers.packagePullSecrets" (dict "root" . "scope" "aws") | nindent 2 }}
