apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ include "providers.fullname" . }}-kubernetes
  labels:
    {{- include "providers.labels" . | nindent 4 }}
  annotations:
    {{- include "providers.annotations" . | nindent 4 }}
spec:
  package: "{{ include "providers.kubernetesRegistry" . }}/provider-kubernetes:{{ .Values.kubernetes.provider.version }}"
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  runtimeConfigRef:
    name: {{ include "providers.runtimeConfigName" . }}
